CREATE TABLE aggregator.news_template
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    item_template character varying(255) COLLATE pg_catalog."default" NOT NULL,
    last_date timestamp without time zone NOT NULL,
    link_template character varying(255) COLLATE pg_catalog."default" NOT NULL,
    source_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    time_template character varying(255) COLLATE pg_catalog."default" NOT NULL,
    time_zone character varying(255) COLLATE pg_catalog."default" NOT NULL,
    title_template character varying(255) COLLATE pg_catalog."default" NOT NULL,
    type character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT news_template_pkey PRIMARY KEY (id),
    CONSTRAINT uk_ee03bxpogx494u2sbl9h7gip2 UNIQUE (source_url)
)

CREATE TABLE aggregator.news
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    link character varying(255) COLLATE pg_catalog."default" NOT NULL,
    pub_date timestamp without time zone NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    news_template_id integer NOT NULL,
    CONSTRAINT news_pkey PRIMARY KEY (id),
    CONSTRAINT fk_news_template_id FOREIGN KEY (news_template_id)
        REFERENCES aggregator.news_template (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)


